render image after get size
archriss/react-native-render-html pull request #417
Opened 2020-10-23 08:27 UTC by sonnt612

### Checks

- [ ] I have read the contribution guidelines regarding Pull Requests here: https://git.io/JJ0Pg 

### Description

2020-10-29 23:18 UTC, jsamr commented
@sonnt612 Thanks for your contribution! The appropriate branch to merge this PR into would be `dev/4.x`, would be nice if your could resubmit.

2020-11-26 07:35 UTC, sonnt612 commented
> @sonnt612 Thanks for your contribution! The appropriate branch to merge this PR into would be `dev/4.x`, would be nice if your could resubmit.

ok. I changed to branch dev/4.x

2020-11-27 09:32 UTC, jsamr commented on src/HTMLImage.js
> +        if (this.state.loading) {
I would have thought you would render the image if it is *not* loading?

2020-11-27 09:32 UTC, jsamr requested changes
See my comments

2020-12-05 18:42 UTC, jsamr commented
I'm closing because this issue has been resolved in v5.0.0 which has a very easy upgrade path from v4.x. See #442

2020-12-05 18:42 UTC, closed without merging